name: Init repository

on:
  push:
    branches:
      - master

jobs:
  init-repository:
    name: Setup store and init repository
    runs-on: ubuntu-latest
    if: |
      github.repository != 'ecomplus/storefront-starter' &&
      contains(github.event.head_commit.message, 'Setup store')

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Remove LICENSE and edit default README
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          rm ./LICENSE
          mv ./.README.md ./README.md
          rm ./.github/workflows/init-repository.yml
          git commit -am "chore(init): remove default license and update readme [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Add views subtree
        run: |
          rm -rf ./template/pages
          git commit -am "chore: remove template/pages to setup subtree"
          git subtree add --prefix=template/pages \
            https://github.com/ecomplus/storefront-starter-views.git master --squash

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
